# ---- Шрифт ----
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# ---- Прозрачность фона 0.50 ----
background_opacity 0.50
dynamic_background_opacity yes

# ---- Cursor trail ----
cursor_trail        3
cursor_trail_decay  0.1 0.4
cursor_trail_start_threshold 2

# ---- Курсор ----
cursor_shape        block
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

# ---- Цвета (базовая схема) ----
foreground            #dddddd
background            #1a1a1a
selection_foreground  #1a1a1a
selection_background  #dddddd

# black
color0  #1a1a1a
color8  #404040
# red
color1  #ff5f5f
color9  #ff8787
# green
color2  #5fff87
color10 #87ffaf
# yellow
color3  #ffff87
color11 #ffffaf
# blue
color4  #5f87ff
color12 #87afff
# magenta
color5  #ff5fff
color13 #ff87ff
# cyan
color6  #5fffff
color14 #87ffff
# white
color7  #dddddd
color15 #ffffff

# ---- Окно ----
window_padding_width 8
hide_window_decorations yes
confirm_os_window_close 0

# ---- Скроллбек ----
scrollback_lines 10000

# ---- Удобства ----
enable_audio_bell no
copy_on_select yes
strip_trailing_spaces smart
include themes/noctalia.conf
